version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region ap-southeast-1)
  build:
    commands:
      - docker build -t hydroponics:latest .
      - docker tag hydroponics:latest 650214975613.dkr.ecr.ap-southeast-1.amazonaws.com/hydroponics:latest
  post_build:
    commands:
      - docker push 650214975613.dkr.ecr.ap-southeast-1.amazonaws.com/hydroponics:latest
      - printf '[{"name":"helloWorld","imageUri":"%s"}]' 650214975613.dkr.ecr.ap-southeast-1.amazonaws.com/hydroponics:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
