version: '3'

services:
  wordpress:
    image: hydroponics:latest
    container_name: hydroponics_wordpress
    volumes: [ ./wordpress/html:/var/www/html ]
    networks:
      - website
      - nginx-wordpress
      - wordpress-internet
  
  nginx:
    image: nginx
    container_name: hydroponics_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
      - ./etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - wordpress
    networks:
      - nginx-wordpress
      - nginx-internet

networks:
  website:
    internal: true
  nginx-wordpress:
    internal: true
  nginx-internet:
    internal: false
  wordpress-internet:
    internal: false
